---
# tasks file for centos_7

# Copyright (C) 2020 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>


- name: enable cache in /etc/yum.conf
  become: yes
  lineinfile:
    path: /etc/yum.conf
    regexp: '^keepcache ='
    line: keepcache = 1
    state: present

- name: upgrade all packages, if CentOS 7
  become: yes
  yum:
    name: "*"
    exclude: docker-ce
    state: latest
  retries: "{{ default_retries }}"
  delay: "{{ default_delay }}"
  register: result
  until: result is succeeded
  tags:
    - common

- name: install epel-release, if CentOS 7
  become: yes
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  retries: "{{ default_retries }}"
  delay: "{{ default_delay }}"
  register: result
  until: result is succeeded
  tags:
    - common

- name: ensure development related packages are installed, if CentOS 7
  become: yes
  yum:
    name: "{{ packages }}"
  retries: "{{ default_retries }}"
  delay: "{{ default_delay }}"
  register: result
  until: result is succeeded
  vars:
    packages:
      - sudo
      - unzip
      - wget
      - lynx
      - nano
      - vim
      - emacs
      - bind-utils
      - bash-completion
      - bash-completion-extras
  tags:
    - common

- name: ensure an up-to-date git is installed, if CentOS 7
  become: yes
  block:
  - name: remove present version
    yum:
      name: git
      state: absent

  - name: ensure IUS repository repo is installed.
    yum:
      name: https://repo.ius.io/ius-release-el7.rpm
      disable_gpg_check: yes
    retries: "{{ default_retries }}"
    delay: "{{ default_delay }}"
    register: result
    until: result is succeeded

  - name: ensure git-core is installed
    yum:
      name: git-core
      state: latest
    retries: "{{ default_retries }}"
    delay: "{{ default_delay }}"
    register: result
    until: result is succeeded
  tags:
    - common
